[project]
name = "ragtools"
version = "0.1.0"
description = "Run RAG tools in command line"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "chonkie[hub]>=1.0.10",
  "fire>=0.7.0",
  "mineru[all]>=2.0.0",
]

[dependency-groups]
dev = [
  "black>=25.1.0",
]
